revoke delete on table "public"."templates" from "anon";

revoke insert on table "public"."templates" from "anon";

revoke references on table "public"."templates" from "anon";

revoke select on table "public"."templates" from "anon";

revoke trigger on table "public"."templates" from "anon";

revoke truncate on table "public"."templates" from "anon";

revoke update on table "public"."templates" from "anon";

revoke delete on table "public"."templates" from "authenticated";

revoke insert on table "public"."templates" from "authenticated";

revoke references on table "public"."templates" from "authenticated";

revoke select on table "public"."templates" from "authenticated";

revoke trigger on table "public"."templates" from "authenticated";

revoke truncate on table "public"."templates" from "authenticated";

revoke update on table "public"."templates" from "authenticated";

revoke delete on table "public"."templates" from "service_role";

revoke insert on table "public"."templates" from "service_role";

revoke references on table "public"."templates" from "service_role";

revoke select on table "public"."templates" from "service_role";

revoke trigger on table "public"."templates" from "service_role";

revoke truncate on table "public"."templates" from "service_role";

revoke update on table "public"."templates" from "service_role";

alter table "public"."templates" drop constraint "templates_user_id_fkey";

alter table "public"."events" drop constraint "events_template_id_fkey";

alter table "public"."templates" drop constraint "templates_pkey";

drop index if exists "public"."templates_pkey";

drop table "public"."templates";


  create table "public"."event_schemas" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "schema_data" jsonb
      );


alter table "public"."event_schemas" enable row level security;

CREATE UNIQUE INDEX templates_pkey ON public.event_schemas USING btree (id);

alter table "public"."event_schemas" add constraint "templates_pkey" PRIMARY KEY using index "templates_pkey";

alter table "public"."event_schemas" add constraint "templates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_schemas" validate constraint "templates_user_id_fkey";

alter table "public"."events" add constraint "events_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.event_schemas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_template_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.user_profiles (id, is_onboarded)
  values (new.id, false);
  return new;
end;
$function$
;

grant delete on table "public"."event_schemas" to "anon";

grant insert on table "public"."event_schemas" to "anon";

grant references on table "public"."event_schemas" to "anon";

grant select on table "public"."event_schemas" to "anon";

grant trigger on table "public"."event_schemas" to "anon";

grant truncate on table "public"."event_schemas" to "anon";

grant update on table "public"."event_schemas" to "anon";

grant delete on table "public"."event_schemas" to "authenticated";

grant insert on table "public"."event_schemas" to "authenticated";

grant references on table "public"."event_schemas" to "authenticated";

grant select on table "public"."event_schemas" to "authenticated";

grant trigger on table "public"."event_schemas" to "authenticated";

grant truncate on table "public"."event_schemas" to "authenticated";

grant update on table "public"."event_schemas" to "authenticated";

grant delete on table "public"."event_schemas" to "service_role";

grant insert on table "public"."event_schemas" to "service_role";

grant references on table "public"."event_schemas" to "service_role";

grant select on table "public"."event_schemas" to "service_role";

grant trigger on table "public"."event_schemas" to "service_role";

grant truncate on table "public"."event_schemas" to "service_role";

grant update on table "public"."event_schemas" to "service_role";


