revoke delete on table "public"."working_sessions" from "anon";

revoke insert on table "public"."working_sessions" from "anon";

revoke references on table "public"."working_sessions" from "anon";

revoke select on table "public"."working_sessions" from "anon";

revoke trigger on table "public"."working_sessions" from "anon";

revoke truncate on table "public"."working_sessions" from "anon";

revoke update on table "public"."working_sessions" from "anon";

revoke delete on table "public"."working_sessions" from "authenticated";

revoke insert on table "public"."working_sessions" from "authenticated";

revoke references on table "public"."working_sessions" from "authenticated";

revoke select on table "public"."working_sessions" from "authenticated";

revoke trigger on table "public"."working_sessions" from "authenticated";

revoke truncate on table "public"."working_sessions" from "authenticated";

revoke update on table "public"."working_sessions" from "authenticated";

revoke delete on table "public"."working_sessions" from "service_role";

revoke insert on table "public"."working_sessions" from "service_role";

revoke references on table "public"."working_sessions" from "service_role";

revoke select on table "public"."working_sessions" from "service_role";

revoke trigger on table "public"."working_sessions" from "service_role";

revoke truncate on table "public"."working_sessions" from "service_role";

revoke update on table "public"."working_sessions" from "service_role";

alter table "public"."working_sessions" drop constraint "working_sessions_pkey";

drop index if exists "public"."working_sessions_pkey";

drop table "public"."working_sessions";


  create table "public"."user_working_sessions" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid default gen_random_uuid(),
    "latest_workspace_id" text
      );


alter table "public"."user_working_sessions" enable row level security;

alter table "public"."workspace_members" add column "is_owner" boolean not null default false;

alter table "public"."workspaces" drop column "updated_at";

CREATE UNIQUE INDEX working_sessions_pkey ON public.user_working_sessions USING btree (id);

alter table "public"."user_working_sessions" add constraint "working_sessions_pkey" PRIMARY KEY using index "working_sessions_pkey";

grant delete on table "public"."user_working_sessions" to "anon";

grant insert on table "public"."user_working_sessions" to "anon";

grant references on table "public"."user_working_sessions" to "anon";

grant select on table "public"."user_working_sessions" to "anon";

grant trigger on table "public"."user_working_sessions" to "anon";

grant truncate on table "public"."user_working_sessions" to "anon";

grant update on table "public"."user_working_sessions" to "anon";

grant delete on table "public"."user_working_sessions" to "authenticated";

grant insert on table "public"."user_working_sessions" to "authenticated";

grant references on table "public"."user_working_sessions" to "authenticated";

grant select on table "public"."user_working_sessions" to "authenticated";

grant trigger on table "public"."user_working_sessions" to "authenticated";

grant truncate on table "public"."user_working_sessions" to "authenticated";

grant update on table "public"."user_working_sessions" to "authenticated";

grant delete on table "public"."user_working_sessions" to "service_role";

grant insert on table "public"."user_working_sessions" to "service_role";

grant references on table "public"."user_working_sessions" to "service_role";

grant select on table "public"."user_working_sessions" to "service_role";

grant trigger on table "public"."user_working_sessions" to "service_role";

grant truncate on table "public"."user_working_sessions" to "service_role";

grant update on table "public"."user_working_sessions" to "service_role";


