revoke delete on table "public"."event_schemas" from "anon";

revoke insert on table "public"."event_schemas" from "anon";

revoke references on table "public"."event_schemas" from "anon";

revoke select on table "public"."event_schemas" from "anon";

revoke trigger on table "public"."event_schemas" from "anon";

revoke truncate on table "public"."event_schemas" from "anon";

revoke update on table "public"."event_schemas" from "anon";

revoke delete on table "public"."event_schemas" from "authenticated";

revoke insert on table "public"."event_schemas" from "authenticated";

revoke references on table "public"."event_schemas" from "authenticated";

revoke select on table "public"."event_schemas" from "authenticated";

revoke trigger on table "public"."event_schemas" from "authenticated";

revoke truncate on table "public"."event_schemas" from "authenticated";

revoke update on table "public"."event_schemas" from "authenticated";

revoke delete on table "public"."event_schemas" from "service_role";

revoke insert on table "public"."event_schemas" from "service_role";

revoke references on table "public"."event_schemas" from "service_role";

revoke select on table "public"."event_schemas" from "service_role";

revoke trigger on table "public"."event_schemas" from "service_role";

revoke truncate on table "public"."event_schemas" from "service_role";

revoke update on table "public"."event_schemas" from "service_role";

alter table "public"."event_schemas" drop constraint "templates_user_id_fkey";

alter table "public"."events" drop constraint "events_template_id_fkey";

alter table "public"."event_schemas" drop constraint "templates_pkey";

drop index if exists "public"."templates_pkey";

drop table "public"."event_schemas";


  create table "public"."templates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "data" jsonb not null
      );


alter table "public"."templates" enable row level security;

alter table "public"."events" add column "date" timestamp with time zone not null;

alter table "public"."events" add column "title" text not null;

alter table "public"."events" alter column "event_data" set not null;

alter table "public"."events" alter column "template_id" set not null;

alter table "public"."events" alter column "workspace_id" set not null;

CREATE UNIQUE INDEX templates_pkey ON public.templates USING btree (id);

alter table "public"."templates" add constraint "templates_pkey" PRIMARY KEY using index "templates_pkey";

alter table "public"."templates" add constraint "templates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."templates" validate constraint "templates_user_id_fkey";

alter table "public"."events" add constraint "events_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.templates(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_template_id_fkey";

grant delete on table "public"."templates" to "anon";

grant insert on table "public"."templates" to "anon";

grant references on table "public"."templates" to "anon";

grant select on table "public"."templates" to "anon";

grant trigger on table "public"."templates" to "anon";

grant truncate on table "public"."templates" to "anon";

grant update on table "public"."templates" to "anon";

grant delete on table "public"."templates" to "authenticated";

grant insert on table "public"."templates" to "authenticated";

grant references on table "public"."templates" to "authenticated";

grant select on table "public"."templates" to "authenticated";

grant trigger on table "public"."templates" to "authenticated";

grant truncate on table "public"."templates" to "authenticated";

grant update on table "public"."templates" to "authenticated";

grant delete on table "public"."templates" to "service_role";

grant insert on table "public"."templates" to "service_role";

grant references on table "public"."templates" to "service_role";

grant select on table "public"."templates" to "service_role";

grant trigger on table "public"."templates" to "service_role";

grant truncate on table "public"."templates" to "service_role";

grant update on table "public"."templates" to "service_role";


